name: "dc.release"
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.ACTIONS_DOCKER_USERNAME }}
      #     password: ${{ secrets.ACTIONS_DOCKER_PASSWORD }}

      # - name: "Publish Features (Docker)"
      #   uses: devcontainers/action@v1
      #   with:
      #     publish-features: "true"
      #     base-path-to-features: "./src"
      #     oci-registry: "docker.io"
      #     features-namespace: "pairspaces"
      #     generate-docs: "true"

      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Publish Features (GHCR)"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          oci-registry: "ghcr.io"
          features-namespace: "pairspaces/devcontaienrs"
          generate-docs: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
